---
title: "EMajor Taiwan"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    include:
      in_header: ["./include/header.html"]
params:
  after_body: ["./include/after_body.html"]
---

```{r serve, eval=F, include=FALSE, message=F}
library(emajorDV)
ws <- webService()
ws$addJs2LatestHtmlServe()
```

```{css}
#calendar {
  -webkit-transform: translate3d(0, 0, 0);
  -moz-transform: translate3d(0, 0, 0);
  transform: translate3d(0, 0, 0);
  width: 420px;
  margin: 0 auto;
  height: 570px;
  overflow: hidden;
}
```


```{r setup, include=FALSE}
library(flexdashboard)
library(httr)
library(dplyr)

```

首頁
========

Input {.sidebar}
-------------------------------------



Column {.tabset}
-----------------------------------------------------------------------

### `r htmltools::HTML("<div class='projectGroup'>專案內容</div>")`{#projectDetail .project}

### `r htmltools::HTML("<div class='videoGroup'>課程影片</div>")`{#courseVideos .course}

```{r}
htmltools::HTML("<iframe src='https://vimeo.com/showcase/7098473/embed' allowfullscreen frameborder='0' style='position:absolute;top:0;left:0;width:100%;height:100%;'></iframe>")
```

Column {.tabset}
-----------------------------------------------------------------------

### `r htmltools::HTML("<div class='projectGroup'>專案</div>")`{#projects .project}

```{r updateJSON, include=FALSE}
# library(drake)

updateJSON = {
  gs <- emajorDV::githubService()
  gs$auth()-> token
  gs$getProjects(token) -> projects
  
  purrr::map_dfr(
    projects,
    ~.x[c("name","body")]
  ) %>%
    rename(
      'project'='name',
      'content'='body'
    ) -> df_projects
  writeLines(
    jsonlite::toJSON(df_projects),
    con="./projects/project.json")
  projects
}


```

<br>
<div id="example">
```{r}
knitr::kable(
  data.frame(
    專案名稱=character(),
    專案內容=character()
  )
)
```
</div>

### `r htmltools::HTML("<div class='videoGroup'>課程清單</div>")`{#courseList .course}

<div id="example2">
```{r}
knitr::kable(
  data.frame(
    主題=character(),
    內容=character(),
    日期=character()
  )
)
```
</div>

行事曆
========

###

<iframe src="https://calendar.google.com/calendar/embed?src=e.major.taiwan%40gmail.com&ctz=Asia%2FTaipei" style="border: 0" width="100%" height="100%" frameborder="0" scrolling="no"></iframe>
